config/routes.rb
Rails.application.routes.draw do

  #
  # API Routes
  #
  # Rather than constraining to subdomain let's match domain beginning with 'api.' so that we
  # can access 'http://api.localhost:3000/' which is closer to the rails convention of using
  # http://localhost:3000.  To get is working you just need to add this to /etc/hosts:
  #   127.0.0.1   api.localhost

  # TODO: let api domain constraint be configurable
  constraints host: /^api\.*./ do
    namespace :api, path: '', defaults: { format: :json } do
      namespace :v1 do
        resources :locations
      end
    end
  end

  #
  # Web Admin Routes
  #

  namespace :admin do
    resources :locations
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: "admin/dashboard#index"
end

app/models/location.rb
class Location < ActiveRecord::Base

  default_scope { order('updated_at DESC') }

  validates_presence_of :name

  geocoded_by :address, latitude: :lat, longitude: :lng
  after_validation :geocode # auto-fetch coordinates

  # The Google Geocode API does not return elevation, but Google does provide an Elevation API.  We'll make a second
  # call to get elevation after the first call geocodes the location.
  before_save :get_elevation
  before_save :geocode_timestamp

  private

  # Returns elevation (in meters)
  # API documentatoin https://developers.google.com/maps/documentation/geocoding/
  def get_elevation
    if self.lat && self.lng
      url = "https://maps.googleapis.com/maps/api/elevation/json?locations=#{self.lat},#{self.lng}"
      uri = URI.parse(url)
      response = Net::HTTP.get(uri)
      self.elevation = JSON.parse(response)['results'].first['elevation'].to_f
    end
  end

  def geocode_timestamp
    if self.lat && self.lng
      self.last_geocoded_at = Time.now
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :timeoutable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_filter :authenticate_admin!

  def authenticate_admin!
    authenticate_user!
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController

  # GET /admin/dashboard
  # GET /admin/dashboard.json
  def index
    
  end

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    params[:per_page] ||= 10
    @q = Location.ransack(params[:q])
    @locations = @q.result(distinct: true).paginate(:page => params[:page], :per_page => params[:per_page])
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to [:admin, @location], notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to [:admin, @location], notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :address, :lat, :lng, :last_geocoded_at, :description, :status, :comments)
    end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  before_action :authenticate

  private
  def authenticate
    if Rails.env.development?
      # TODO accept token via url param
      true
    else
      # TODO reenable token requirement
#      authenticate_or_request_with_http_token do |token, options|
        # TODO check token
        true
#      end
    end
  end

end

app/controllers/api/v1/locations_controller.rb
module Api
  module V1
    class LocationsController < Api::V1::ApiController
      respond_to :json
      RESULT_TOTAL = 10
      def index
        me = Location.new(location_params)
        local_locations = Location.near(me, 25).reorder("RANDOM()").limit(5)
        any_locations = Location.where('last_geocoded_at IS NOT NULL').where('id NOT IN (?)', local_locations.ids).reorder("RANDOM()").limit(RESULT_TOTAL - local_locations.size)
        locations = local_locations + any_locations
        locations.shuffle!
        respond_with locations
      end

      private

      # Never trust parameters from the scary internet, only allow the white list through.
      def location_params
        params.permit(:lat, :lng)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)

    case level
    when :notice then "alert-info"
    when :info then "alert-info"
    when :success then "alert-success"
    when :error then "alert-danger"
    when :alert then "alert-warning"
    when :warn then "alert-warning"
    else
      level
    end
  end
end

app/views/admin/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

<!-- TODO -->
<h4>No links work currently, except for logout in the user menu.</h4>

app/views/admin/locations/_form.html.erb
<%= form_for([:admin, @location]) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: 'form-control'  %>

    <%= f.label :address %><br>
    <%= f.text_field :address, class: 'form-control' %>

    <br/>

    <div class="panel panel-green">
      <div class="panel-heading">
        Geocoding and Elevation
      </div>
      <div class="panel-body">

        <%= f.label :lat %>
        <%= @location.lat || 'No latitude' %>

        <span class="spacer-md"></span>

        <%= f.label :lng || 'No longitude' %>
        <%= @location.lng %>

        <span class="spacer-md"></span>

        <%= f.label :elevation %>
        <%= @location.elevation  || 'No Elevation'%>

        <span class="spacer-md"></span>

        <%= link_to "Show Map", admin_location_path(@location) if @location.id %>

      </div>
      <div class="panel-footer">
        Last updated <%= @location.last_geocoded_at || 'never' %>
      </div>
    </div>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>

    <%= f.label :status %>
    <%= f.text_field :status, class: 'form-control' %>

    <%= f.label :comments %>
    <%= f.text_area :comments, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit (@location.id ? 'Update' : 'Save') + " Location", class: 'btn btn-primary'%>
    <span class="spacer"></span>
    <%= link_to 'Back', admin_locations_path, class: 'btn btn-primary btn-outline btn-sm' %>
  </div>

<% end %>

app/views/admin/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

app/views/admin/locations/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Locations</h1>
    <div class="panel">
      <div class="panel-footer">
        <%= link_to 'New Location', new_admin_location_path, class: 'btn btn-default btn-outline' %>
      </div>
    </div>
  </div>
</div>

<%= search_form_for [:admin, @q], class: 'form-inline' do |f| %>
  <div class="row">
    <div class="col-sm-6">
      Show <%= select_tag :per_page,  options_for_select([10, 20, 50, 100], params[:per_page]), class: 'form-control', onchange: '$("#location_search").submit();' %> entries
    </div>
    <div class="col-sm-6">
      <div class="search-form pull-right">
        <div class="form-group">
          <label>Search <%= f.search_field :name_or_address_cont, placeholder: "Name or Address", class: 'form-control', style: 'width=130%' %>
          </label>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="divider-sm"></div>

<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped table-bordered table-hover dataTable no-footer" >
      <thead>
        <tr>
          <th><%= sort_link(@q, :name) %></th>
          <th><%= sort_link(@q, :address) %></th>
          <th><%= sort_link(@q, :lat) %>, <%= sort_link(@q, :lng) %></th>
          <th><%= sort_link(@q, :elevation) %></th>
          <th><%= sort_link(@q, :last_geocoded_at) %></th>
          <th><%= sort_link(@q, :status) %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @locations.each do |location| %>
        <tr>
          <td><%= location.name %></td>
          <td><%= location.address %></td>
          <td><%= location.lat %>, <%= location.lng %></td>
          <td><%= location.elevation.to_i %> m</td>
          <td><%= l(location.last_geocoded_at.to_date, format: :short) if location.last_geocoded_at %></td>
          <td><%= location.status %></td>
          <td><%= link_to 'Show', [:admin, location] %></td>
          <td><%= link_to 'Edit', edit_admin_location_path(location) %></td>
          <td><%= link_to 'Destroy', [:admin, location], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <p>Showing <%= @locations.offset + 1 %> - <%= ((@locations.per_page + @locations.offset) < @locations.total_entries) ? (@locations.per_page + @locations.offset) : @locations.total_entries %> <%= "of #{@locations.total_entries}" unless @locations.total_pages == @locations.current_page  %> results.</p>
  </div>
  <div class="col-sm-6">
    <%= will_paginate @locations, inner_window: 2, renderer: BootstrapPagination::Rails, class: 'pull-right' %>
  </div>
</div>

app/views/admin/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_locations_path %>

app/views/admin/locations/show.html.erb
<% content_for :head do %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<% end %>

<h1><%= @location.name %></h1>

<div>
  <div id="map" style='height: 500px;'></div>
</div>


<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @location.lng %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @location.elevation %>
</p>

<p>
  <strong>Last geocoded at:</strong>
  <%= @location.last_geocoded_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @location.status %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @location.comments %>
</p>

<script type="text/javascript">
  $(function() {

    handler = Gmaps.build('Google');
    handler.buildMap({
      provider: {
        zoom: 16,
        center: new google.maps.LatLng(<%= @location.lat %>, <%= @location.lng %>)
      },
      internal: {id: 'map'}
      }, function(){
      markers = handler.addMarkers([
        {
          "lat": <%= @location.lat %>,
          "lng": <%= @location.lng %>,
          "infowindow": "<%= @location.name %><br><%= @location.address %>",
        }
      ]);
      handler.bounds.extendWith(markers);

      // JR: with a single marker we don't need to fitMapToBounds, else it zooms in fully
      //handler.fitMapToBounds();
    });
  });
</script>

<%= link_to 'Edit', edit_admin_location_path(@location) %> |
<%= link_to 'Back', admin_locations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>Pointing Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">

        <!-- menu button for mobile sizes -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- logo -->
        <%= link_to root_url, class: 'navbar-brand' do %> <i class="logo-arrow fa fa-location-arrow fa-2x"></i>
        Pointing &nbsp;Administration
        <% end %>

      </div><!-- end navbar-header -->

      <!-- top navbar menus -->
      <%= render 'shared/user_menu' if user_signed_in? %>

      <!-- primary navigation sidebar -->
      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <%= render_navigation(:level =>1..2, :expand_all => true) %>
        </div>
      </div>
      
    </nav>
    
    <!-- flash messages for error, success, notice, warning etc. -->
    <div class="page-wrapper-marginless">
      <%= render 'shared/flash_messages' %>
    </div>
    
    <!-- start main content -->
    <div id="page-wrapper" style="min-height: 350px;">
        <%= yield -%>
    </div>
    <!-- end main content -->
  </div>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert alert-dismissable <%= flash_class(key.to_sym) %> fade in">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/shared/_user_menu.html.erb
<ul class="nav navbar-top-links navbar-right">

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-user fa-fw"></i>
      <%= current_user.email %> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <li>
        <a href="#">
          <i class="fa fa-user fa-fw"></i>
          User Profile
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-gear fa-fw"></i>
          Settings
        </a>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out fa-fw"></i>
        Logout
        <% end %></a>
    </li>
  </ul>
</ul>